"""initial_foundation"""
from alembic import op
import sqlalchemy as sa

revision = '59d9da2013e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sample', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trade_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{6}$'", name=op.f('ck_funds_six_digit_code')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_funds'))
    )
    op.create_index(op.f('ix_funds_name'), 'funds', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('fund_navs',
    sa.Column('fund_code', sa.String(length=6), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cumulative_nav', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.CheckConstraint('cumulative_nav IS NULL OR cumulative_nav > 0', name=op.f('ck_fund_navs_positive_cumulative_nav')),
    sa.CheckConstraint('unit_nav > 0', name=op.f('ck_fund_navs_positive_nav')),
    sa.ForeignKeyConstraint(['fund_code'], ['funds.code'], name=op.f('fk_fund_navs_fund_code_funds')),
    sa.PrimaryKeyConstraint('fund_code', 'nav_date', name=op.f('pk_fund_navs'))
    )
    op.create_table('simulation_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_cash >= 0', name=op.f('ck_simulation_accounts_nonnegative_cash')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulation_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_accounts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_simulation_accounts_user_id'))
    )
    op.create_table('watchlists',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fund_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_code'], ['funds.code'], name=op.f('fk_watchlists_fund_code_funds')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'fund_code', name=op.f('pk_watchlists'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('simulation_accounts')
    op.drop_table('fund_navs')
    op.drop_table('users')
    op.drop_index(op.f('ix_funds_name'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
