"""cash dividend events payments and data update jobs"""
from alembic import op
import sqlalchemy as sa

revision = 'bac0bcf6b651'
down_revision = 'd8be352ddbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_update_jobs',
    sa.Column('fund_code', sa.String(length=6), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['fund_code'], ['funds.code'], name=op.f('fk_data_update_jobs_fund_code_funds')),
    sa.PrimaryKeyConstraint('fund_code', name=op.f('pk_data_update_jobs'))
    )
    op.create_table('dividend_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fund_code', sa.String(length=6), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('cash_per_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('observed', 'verified', 'conflict')", name=op.f('ck_dividend_events_valid_status')),
    sa.CheckConstraint('cash_per_share > 0', name=op.f('ck_dividend_events_positive_distribution')),
    sa.CheckConstraint('pay_date >= record_date AND (ex_date IS NULL OR (ex_date >= record_date AND pay_date >= ex_date))', name=op.f('ck_dividend_events_valid_dates')),
    sa.ForeignKeyConstraint(['fund_code'], ['funds.code'], name=op.f('fk_dividend_events_fund_code_funds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividend_events')),
    sa.UniqueConstraint('fund_code', 'record_date', name=op.f('uq_dividend_events_fund_code'))
    )
    op.create_index(op.f('ix_dividend_events_fund_code'), 'dividend_events', ['fund_code'], unique=False)
    op.create_table('dividend_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND paid_at IS NULL) OR (status = 'paid' AND paid_at IS NOT NULL)", name=op.f('ck_dividend_payments_valid_payment')),
    sa.CheckConstraint('shares >= 0 AND amount >= 0', name=op.f('ck_dividend_payments_nonnegative_entitlement')),
    sa.ForeignKeyConstraint(['account_id'], ['simulation_accounts.id'], name=op.f('fk_dividend_payments_account_id_simulation_accounts')),
    sa.ForeignKeyConstraint(['event_id'], ['dividend_events.id'], name=op.f('fk_dividend_payments_event_id_dividend_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividend_payments')),
    sa.UniqueConstraint('account_id', 'event_id', name=op.f('uq_dividend_payments_account_id'))
    )
    op.create_index(op.f('ix_dividend_payments_account_id'), 'dividend_payments', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text('SELECT EXISTS (SELECT 1 FROM dividend_payments)')):
        raise RuntimeError('存在分红权益账本，禁止降级删除审计记录。')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_payments_account_id'), table_name='dividend_payments')
    op.drop_table('dividend_payments')
    op.drop_index(op.f('ix_dividend_events_fund_code'), table_name='dividend_events')
    op.drop_table('dividend_events')
    op.drop_table('data_update_jobs')
    # ### end Alembic commands ###
